apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-rtdx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-rtdx
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-rtdx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-rtdx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-rtdx
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-knpc-tenant/dotnet-component/devfile-sample-dotnet60-basic-rtdx@sha256:f809fa4f6a260f86d87f1a1c813150289601a95da4e60a65e1d3e7b132bbac4c
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
